### ISSUE TITLE
If you could stick any action figure in your ear, which would you pick and why?

### ISSUE THREAD

**Issue by jhil** [callmecavs/ama#4]

**Comment by jaxgeller** [comment]
This ^

**Comment by callmecavs** [comment]
Easiest question yet. It would definitely be a Buzz Lightyear action figure, as pictured below. This guy was my favorite growing up, because of the hilarious lines he says when you press the different buttons. Those are probably the only sounds I wouldn't get tired of hearing all the time.

> "To infinity, and beyond!" 🚀 

![Buzz Lightyear](http://ecx.images-amazon.com/images/I/815AL782IxL._SL1500_.jpg)
