### ISSUE TITLE
What's the best way to sort one million 32bit integers?

### ISSUE THREAD

**Issue by josh-ua** [callmecavs/ama#5]

**Comment by callmecavs** [comment]
@josh-ua you get this in an interview haha?

its a question you're gonna get a lot of different answers to, depending on what you mean by "best". immediately when i see the word "sort", I think quicksort or a fancier variety of it (introsort for example). the algorithm of choice is often influenced by more than just pure big O complexity tho.

* what language are you using to sort them?
* are there memory constraints (some sorting algos require a ton of intermediate calculations)?
* do we know what range all the numbers are going to be in (radix sort could be effective if there's a range of possible numbers, rather than assuming negative infinity to infinity)?

when in doubt, ~pinky out~ quicksort. i think the right answer here tho is "need more info" to be able to explain the best choice beyond just naming fast general purpose sorting algos.

as with everything in programming, there's theory, and then there's real software, limited by real constraints, aiming to solve a specific problem.
